// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3dYNHlAcFJkVTfDHkm49K8wfCx5P8DpE',
    appId: '1:617161514571:web:fed1b364a0991dab4f37ce',
    messagingSenderId: '617161514571',
    projectId: 'flutter-moto-cart',
    authDomain: 'flutter-moto-cart.firebaseapp.com',
    storageBucket: 'flutter-moto-cart.appspot.com',
    measurementId: 'G-72JB0R6H8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDPeSWJzxtJuC64b9VQPzshYR93hgvZ8c',
    appId: '1:617161514571:android:b5d9da7c4ffdaab54f37ce',
    messagingSenderId: '617161514571',
    projectId: 'flutter-moto-cart',
    storageBucket: 'flutter-moto-cart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtkGIBH68v8JCVUlSwMMy3BDiXVuY9jdg',
    appId: '1:617161514571:ios:1ce887eb133b01de4f37ce',
    messagingSenderId: '617161514571',
    projectId: 'flutter-moto-cart',
    storageBucket: 'flutter-moto-cart.appspot.com',
    iosClientId: '617161514571-3ipsqadptljs7bj78vqte2simr8gr048.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
